---
- name: Download oracle jdk rpm package
  become: yes
  get_url:
    url: "{{ jdk_download_url }}"
    dest: "{{jdk_download_dest_path}}"
    headers: 'Cookie: oraclelicense=accept-securebackup-cookie'
    checksum: "{{ checksum }}"

- name: Install oracle_jdk from local package
  become: yes
  yum:
    name: "{{jdk_download_dest_path}}"
