---
- name: Add gocd yum repository
  become: yes
  yum_repository:
    name: gocd
    description: gocd repo
    baseurl: https://download.gocd.io
    gpgcheck: yes
    gpgkey: https://download.gocd.io/GOCD-GPG-KEY.asc
    enabled: yes

- name: Install go agent {{version}}
  become: yes
  yum:
    name: go-agent-{{version}}

- name: Register agent with go-server
  become: yes
  lineinfile:
    path: /etc/default/go-agent
    regexp: '^GO_SERVER_URL='
    line: 'GO_SERVER_URL=https://{{go_server_location}}:8154/go'
  notify: Restart go agent

- name: Enable agent on go server
  become: yes
  copy:
    src: autoregister.properties
    dest: /var/lib/go-agent/config/autoregister.properties
  notify: Restart go agent
